# Codemagic CI configuration for cloud iOS builds (Capacitor)

workflows:
  ios_testflight:
    name: iOS TestFlight
    max_build_duration: 60
    environment:
      xcode: 15.4
      cocoapods: default
      node: 20.15.0
      groups:
        - app_store_connect
        - ios_signing
      vars:
        XCODE_SCHEME: App
        BUNDLE_IDENTIFIER: app.lovable.a97379e496a1241fea9bafbc36edce731
        # ⚠️ IMPORTANT: Add this to vars or your ios_signing group
        # Replace ABC123XYZ9 with your real Apple Developer Team ID
        DEVELOPMENT_TEAM: 6547583QJL
    cache:
      cache_paths:
        - ~/.npm
        - ~/.cache/CocoaPods
        - $CM_BUILD_DIR/node_modules
        - ios/App/Pods
    scripts:
      - name: Preflight - verify App Store Connect variables
        script: |
          set -e
          echo "Checking Codemagic environment variables for App Store Connect..."
          missing=0
          if [ -z "${APP_STORE_KEY_ID}" ]; then echo "ERROR: APP_STORE_KEY_ID is missing."; missing=1; fi
          if [ -z "${APP_STORE_ISSUER_ID}" ]; then echo "ERROR: APP_STORE_ISSUER_ID is missing."; missing=1; fi
          if [ -z "${APP_STORE_P8}" ]; then echo "ERROR: APP_STORE_P8 is missing."; missing=1; fi
          if [ "$missing" -eq 1 ]; then echo "One or more required variables are missing. Failing early."; exit 1; fi
          if ! echo "$APP_STORE_P8" | grep -q "BEGIN PRIVATE KEY"; then echo "ERROR: APP_STORE_P8 does not contain a valid BEGIN PRIVATE KEY."; exit 1; fi
          echo "✅ Preflight OK."
      - name: Install dependencies
        script: |
          npm ci
          npm install -g @capacitor/cli
      - name: Build web assets
        script: |
          npm run build
      - name: Setup iOS platform (Capacitor)
        script: |
          if [ -d "ios" ]; then
            echo "Removing existing iOS directory..."
            rm -rf ios
          fi
          echo "Adding iOS platform..."
          npx cap add ios
      - name: Install iOS dependencies
        script: |
          npx cap sync ios
          cd ios/App && pod install
      - name: Debug environment variables
        script: |
          echo "Environment variables:"
          echo "APP_STORE_KEY_ID length: ${#APP_STORE_KEY_ID}"
          echo "APP_STORE_ISSUER_ID length: ${#APP_STORE_ISSUER_ID}"
          echo "APP_STORE_P8 length: ${#APP_STORE_P8}"
          echo "DEVELOPMENT_TEAM: $DEVELOPMENT_TEAM"
          echo "BUNDLE_IDENTIFIER: $BUNDLE_IDENTIFIER"
      - name: 🔍 Show first line of .p8 key
        script: |
          echo "First line of APP_STORE_P8:"
          echo "$APP_STORE_P8" | head -n 1
      - name: Set up automatic code signing  
        script: |
          cd $CM_BUILD_DIR
          echo "🔑 Fetching signing files..."
          app-store-connect fetch-signing-files "$BUNDLE_IDENTIFIER" \
            --issuer-id "$APP_STORE_ISSUER_ID" \
            --key-id "$APP_STORE_KEY_ID" \
            --private-key "$APP_STORE_P8" \
            --type IOS_APP_STORE \
            --create
          echo "🔐 Adding certificates to keychain..."
          keychain add-certificates
          cd ios/App
          echo "🔧 Applying provisioning profiles to project..."
          xcode-project use-profiles

          echo "🔎 Debug: Code signing settings..."
          xcodebuild -showBuildSettings -scheme "$XCODE_SCHEME" | grep -i signing

          echo "📐 Forcing CODE_SIGN_STYLE to Automatic..."
          sed -i '' 's/CODE_SIGN_STYLE = Manual/CODE_SIGN_STYLE = Automatic/g' App.xcodeproj/project.pbxproj
      - name: 🔍 List shared Xcode schemes
        script: |
          cd ios/App
          xcodebuild -list
      - name: Archive (Release)
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -allowProvisioningUpdates \
            clean archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM"
      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -exportOptionsPlist "$CM_EXPORT_OPTIONS" \
            -exportPath "$CM_BUILD_DIR/build/ipa"
    artifacts:
      - build/ipa/*.ipa
      - build/App.xcarchive
    publishing:
      app_store_connect:
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        api_key: $APP_STORE_P8
        submit_to_testflight: true
