# Codemagic CI configuration for cloud iOS builds (Capacitor)
# Docs: https://docs.codemagic.io/yaml-basic-configuration/yaml-builds/

workflows:
  ios_testflight:
    name: iOS TestFlight
    max_build_duration: 60
    environment:
      xcode: 15.4
      cocoapods: default
      node: 20.15.0
      # Create these groups in Codemagic UI and add required variables:
      # - app_store_connect: APP_STORE_KEY_ID, APP_STORE_ISSUER_ID, APP_STORE_P8
      # - ios_signing: DEVELOPMENT_TEAM
      groups:
        - app_store_connect
        - ios_signing
      vars:
        XCODE_SCHEME: App
        BUNDLE_IDENTIFIER: app.lovable.97379e496a1241fea9bafbc36edce731
    cache:
      cache_paths:
        - ~/.npm
        - ~/.cache/CocoaPods
        - $CM_BUILD_DIR/node_modules
        - ios/App/Pods
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web assets
        script: |
          npm run build
      - name: Prepare iOS platform (Capacitor)
        script: |
          npx cap sync ios
          cd ios/App
          pod install
      - name: Set up automatic code signing
        script: |
          cd $CM_BUILD_DIR
          app-store-connect fetch-signing-files "$BUNDLE_IDENTIFIER" --type IOS_APP_STORE --create
          keychain add-certificates
          cd ios/App
          xcode-project use-profiles
      - name: Archive (Release)
        script: |
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            clean archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM"
      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -exportOptionsPlist "$CM_EXPORT_OPTIONS" \
            -exportPath "$CM_BUILD_DIR/build/ipa"
    artifacts:
      - build/ipa/*.ipa
      - build/App.xcarchive
    publishing:
      app_store_connect:
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        private_key: $APP_STORE_P8
        submit_to_testflight: true
