# Codemagic CI configuration for cloud iOS builds (Capacitor)

workflows:
  ios_testflight:
    name: iOS TestFlight
    max_build_duration: 60
    environment:
      xcode: 15.4
      cocoapods: default
      node: 20.15.0
      groups:
        - app_store_connect
        - ios_signing
      vars:
        XCODE_SCHEME: App
        BUNDLE_IDENTIFIER: app.lovable.a97379e496a1241fea9bafbc36edce731
    cache:
      cache_paths:
        - ~/.npm
        - ~/.cache/CocoaPods
        - $CM_BUILD_DIR/node_modules
        - ios/App/Pods
    scripts:
      - name: Preflight - verify App Store Connect variables
        script: |
          set -e
          echo "Checking Codemagic environment variables for App Store Connect..."
          missing=0
          if [ -z "${APP_STORE_KEY_ID}" ]; then echo "ERROR: APP_STORE_KEY_ID is missing. Attach the 'app_store_connect' env group or set the variable."; missing=1; fi
          if [ -z "${APP_STORE_ISSUER_ID}" ]; then echo "ERROR: APP_STORE_ISSUER_ID is missing."; missing=1; fi
          if [ -z "${APP_STORE_P8}" ]; then echo "ERROR: APP_STORE_P8 (p8 private key) is missing."; missing=1; fi
          if [ "$missing" -eq 1 ]; then echo "One or more required variables are missing. Failing early."; exit 1; fi
          if ! echo "$APP_STORE_P8" | grep -q "BEGIN PRIVATE KEY"; then echo "ERROR: APP_STORE_P8 does not contain a valid -----BEGIN PRIVATE KEY----- header."; exit 1; fi
          echo "Preflight OK."
      - name: Install dependencies
        script: |
          npm ci
          npm install -g @capacitor/cli
      - name: Build web assets
        script: |
          npm run build
      - name: Setup iOS platform (Capacitor)
        script: |
          if [ -d "ios" ]; then
            echo "Removing existing iOS directory..."
            rm -rf ios
          fi
          echo "Adding iOS platform..."
          npx cap add ios
      - name: Install iOS dependencies
        script: |
          npx cap sync ios
          cd ios/App && pod install
      - name: Debug environment variables
        script: |
          echo "Checking environment variables..."
          echo "APP_STORE_KEY_ID length: ${#APP_STORE_KEY_ID}"
          echo "APP_STORE_ISSUER_ID length: ${#APP_STORE_ISSUER_ID}"
          echo "APP_STORE_P8 length: ${#APP_STORE_P8}"
          echo "DEVELOPMENT_TEAM length: ${#DEVELOPMENT_TEAM}"
          echo "BUNDLE_IDENTIFIER: $BUNDLE_IDENTIFIER"
          
          if [ -z "$APP_STORE_P8" ]; then
            echo "ERROR: APP_STORE_P8 is empty"
            exit 1
          fi
          
          if [ -z "$APP_STORE_KEY_ID" ]; then
            echo "ERROR: APP_STORE_KEY_ID is empty"
            exit 1
          fi
          
          if [ -z "$APP_STORE_ISSUER_ID" ]; then
            echo "ERROR: APP_STORE_ISSUER_ID is empty"
            exit 1
          fi
          
          echo "Environment variables appear to be set"
      - name: Set up automatic code signing  
        script: |
          cd $CM_BUILD_DIR
          app-store-connec
