# Codemagic CI configuration for cloud iOS builds (Capacitor)

workflows:
  ios_testflight:
    name: iOS TestFlight
    max_build_duration: 60
    environment:
      xcode: 15.4
      cocoapods: default
      node: 20.15.0
      groups:
        - app_store_connect
        - ios_signing
      vars:
        XCODE_SCHEME: App
        BUNDLE_IDENTIFIER: com.academyhealth.knoMe  # Get this from Apple Developer Console
        DEVELOPMENT_TEAM: 6547583QJL  # Your Apple Developer Team ID
    cache:
      cache_paths:
        - ~/.npm
        - ~/.cache/CocoaPods
        - $CM_BUILD_DIR/node_modules
        - ios/App/Pods
    scripts:
      - name: Preflight - verify App Store Connect variables
        script: |
          set -e
          echo "Checking App Store Connect variables..."
          missing=0
          if [ -z "${APP_STORE_KEY_ID}" ]; then echo "❌ APP_STORE_KEY_ID missing"; missing=1; fi
          if [ -z "${APP_STORE_ISSUER_ID}" ]; then echo "❌ APP_STORE_ISSUER_ID missing"; missing=1; fi
          if [ -z "${APP_STORE_P8}" ]; then echo "❌ APP_STORE_P8 missing"; missing=1; fi
          if [ "$missing" -eq 1 ]; then exit 1; fi
          # Skip header check for base64 encoded content
          echo "✅ Preflight passed"
      - name: Install dependencies
        script: |
          npm ci
          npm install -g @capacitor/cli
      - name: Build web assets
        script: |
          npm run build
      - name: Setup iOS platform (Capacitor)
        script: |
          if [ -d "ios" ]; then rm -rf ios; fi
          npx cap add ios
      - name: Install iOS dependencies
        script: |
          npx cap sync ios
          cd ios/App && pod install
      - name: Debug environment variables
        script: |
          echo "TEAM: $DEVELOPMENT_TEAM"
          echo "SCHEME: $XCODE_SCHEME"
          echo "APP_STORE_KEY_ID length: ${#APP_STORE_KEY_ID}"
          echo "APP_STORE_P8 first line:"
          echo "$APP_STORE_P8" | head -n 1
      - name: Set up code signing
        script: |
          set -e
          echo "🔍 Setting up code signing with App Store Connect API..."
          
          # Debug private key format
          echo "🔍 Private key format check:"
          echo "Key length: ${#APP_STORE_P8}"
          echo "First line: $(echo "$APP_STORE_P8" | head -n 1)"
          echo "Last line: $(echo "$APP_STORE_P8" | tail -n 1)"
          echo "Contains BEGIN: $(echo "$APP_STORE_P8" | grep -c "BEGIN PRIVATE KEY" || echo "0")"
          echo "Contains END: $(echo "$APP_STORE_P8" | grep -c "END PRIVATE KEY" || echo "0")"
          
          # Initialize keychain
          keychain initialize
          
          # Create private key file and verify it (decode base64)
          echo "$APP_STORE_P8" | base64 -d > ~/private_key.p8
          echo "🔍 Created key file size: $(wc -c < ~/private_key.p8)"
          
          # Fetch signing files using App Store Connect API
          app-store-connect fetch-signing-files "$BUNDLE_IDENTIFIER" \
            --issuer-id "$APP_STORE_ISSUER_ID" \
            --key-id "$APP_STORE_KEY_ID" \
            --private-key "$APP_STORE_P8" \
            --type IOS_APP_STORE \
            --create
          
          # Add certificates to keychain
          keychain add-certificates
          
          # Configure Xcode project
          cd ios/App
          xcode-project use-profiles
      - name: Archive (Release)
        script: |
          set -e
          cd ios/App
          
          echo "🔍 Building for App Store distribution..."
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            clean archive
      - name: Export IPA
        script: |
          # Create export options plist
          cat > ~/export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$DEVELOPMENT_TEAM</string>
          </dict>
          </plist>
          EOF
          
          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -exportOptionsPlist ~/export_options.plist \
            -exportPath "$CM_BUILD_DIR/build/ipa"
    artifacts:
      - build/ipa/*.ipa
      - build/App.xcarchive
    publishing:
      app_store_connect:
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        api_key: $APP_STORE_P8
        submit_to_testflight: true
